version: "3"
services:
  openvpn-as:
    build: .
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - INTERFACE=eth0 #optional
    volumes:
      - ./data:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    restart: always
